-- 11.DISPLAY THE LIST OF EMPLOYEES WHO HAVE JOINED A COMPANY BEFORE 1980 OR AFTER 1988. 
select * from emp where HIREDATE not between '1980-01-01' and '1988-12-31';

-- 12.WAQTD THE NAMES OF THE EMPLOYEES WORKING IN DEPT 10,20,40 OR EMPLOYEE WORKING AS CLERK,SALESMAN,ANALYST. 
select ename from emp where DEPTNO in (10,20,40) or JOB in ('CLERK','SALESMAN','ANALYST');

-- 13.WAQTD THE NAME OF THE EMPLOYEES WHOSE NAME STARTS WITH 'S' AND HAVING FIVE CHARACTERS. 
select ename from emp where ename like 's____';

-- 14.WAQTD THE NAME OF THE EMPLOYEES WHO ARE NOT GET COMM AND WORKING DEPTNO 10,20. 
select ename from emp where COMM is null and DEPTNO in (10,20);

-- 15.WAQTD DETAILS OF THE EMPLOYEES ALONG WITH ANNUAL SALARY IF THEY ARE WORKING MANAGER DEPT AS 20,30 AND THEIR ANNUAL SALARY GREATER THAN 12000. 
select *,sal*12 as 'Annual Salary' from emp where (job = 'manager' and DEPTNO in (20,30)) and sal*12 > 12000;

-- 16.WAQTD DETAILS OF EMPLOYEES WHO ARE HIRED in FEB. 
select * from emp where month(HIREDATE)=2;

-- 17.WAQTD DETAILS OF EMPLOYEES ALONG WITH ANNUAL SALARY WHOSE NAME STARTS 'M' AND LAST BUT FIRST CHARACTER 'S'. 
select *,sal*12 as 'ANNUAL SALARY' from emp where ename like 'm%s';

-- 18.WAQTD NAME AND HIREDATE OF EMPLOYEES WHO ARE HIRED BETWEEN JAN-81 AND DEC 81 
select ename,hiredate from emp where hiredate between '1981-01-01' and '1981-12-31';

-- 19.WAQTD SALESMAN DETAILS. 
select * from emp where job='salesman';

-- 20.WAQTD DEPT DETAILS OF 10,20.
select * from emp where DEPTNO in (10,20);